# Generated by Django 5.1.3 on 2024-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1)),
                ('winner', models.CharField(default='pending', max_length=10)),
                ('round', models.IntegerField(default=0)),
                ('board', models.JSONField(default=list)),
            ],
        ),
    ]
