# Generated by Django 5.1.3 on 2024-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
